using System.Text;
using System.Text.Json;
using System.Text.RegularExpressions;
using Lumina;

var repoRoot = FindRepoRoot()
    ?? throw new InvalidOperationException("Could not find repo root (NoMoreEquals.sln).");

var gamePath = args.Length > 0
    ? args[0]
    : FfxivLocator.FindInstallPath()
      ?? throw new InvalidOperationException(
          "FFXIV install not found. Pass the game root as argv[0], e.g.\n" +
          "  dotnet run --project tools/FontProbe/FontProbe -- \"C:\\Path\\To\\FINAL FANTASY XIV - A Realm Reborn\"");

var sqpack = Path.Combine(gamePath, "game", "sqpack");
if (!Directory.Exists(sqpack))
    throw new DirectoryNotFoundException($"Missing sqpack under game path: {sqpack}");

var outPath = args.Length > 1
    ? args[1]
    : Path.Combine(repoRoot, "NoMoreEquals", "Data", "KanjiMap.cs");
var candidatesPath = args.Length > 2
    ? args[2]
    : Path.Combine(repoRoot, "NoMoreEquals", "Data", "KanjiCandidates.cs");

Console.OutputEncoding = Encoding.UTF8;
Console.WriteLine($"Game:   {gamePath}");
Console.WriteLine($"SqPack: {sqpack}");
var lumina = new GameData(sqpack);
var file = lumina.GetFile("common/font/AXIS_12.fdt") ?? throw new Exception("AXIS_12.fdt not found");
var data = file.Data;
Console.WriteLine($"AXIS_12.fdt bytes: {data.Length}");

var fontHeaderOffset = BitConverter.ToInt32(data, 8);
const int fontTableHeaderSize = 32;
var glyphCount = BitConverter.ToInt32(data, fontHeaderOffset + 4);
var glyphs = new HashSet<char>();
for (var i = 0; i < glyphCount; i++)
{
    // FontTableEntry is 16 bytes.
    var offset = fontHeaderOffset + fontTableHeaderSize + (i * 16);
    var charUtf8 = BitConverter.ToInt32(data, offset);
    var cp = CodePointFromUtf8Int32(charUtf8);
    if (cp > 0 && cp <= 0xFFFF)
        glyphs.Add((char)cp);
}

Console.WriteLine($"Glyphs in AXIS_12: {glyphs.Count}");

var candText = File.ReadAllText(candidatesPath, Encoding.UTF8);
var candidates = new Dictionary<char, char>();
foreach (Match m in Regex.Matches(candText, @"\['\\u([0-9A-Fa-f]{4})'\]\s*=\s*'\\u([0-9A-Fa-f]{4})'"))
{
    var zh = (char)Convert.ToInt32(m.Groups[1].Value, 16);
    var jp = (char)Convert.ToInt32(m.Groups[2].Value, 16);
    candidates[zh] = jp;
}

Console.WriteLine($"Candidates: {candidates.Count}");

var active = candidates
    .Where(kv => !glyphs.Contains(kv.Key) && glyphs.Contains(kv.Value))
    .OrderBy(kv => (int)kv.Key)
    .ToList();

Console.WriteLine($"Active (missing zh, present jp): {active.Count}");
foreach (var c in new[] { '綠', '绿', '黑', '每', '圖', '邊', '國', '學', '緑', '黒', '毎' })
{
    candidates.TryGetValue(c, out var jp);
    var hasMap = candidates.ContainsKey(c);
    var isActive = hasMap && !glyphs.Contains(c) && glyphs.Contains(jp);
    Console.WriteLine(
        $"  U+{(int)c:X4} inFont={glyphs.Contains(c)} map={(hasMap ? $"U+{(int)jp:X4}" : "n/a")} active={isActive}");
}

var sb = new StringBuilder();
sb.AppendLine("// <auto-generated />");
sb.AppendLine("// Filtered against international AXIS_12.fdt glyph coverage.");
sb.AppendLine("// Only Chinese/kyujitai forms missing from AXIS, whose Japanese form exists.");
sb.AppendLine("using System.Collections.Generic;");
sb.AppendLine();
sb.AppendLine("namespace NoMoreEquals.Data;");
sb.AppendLine();
sb.AppendLine("internal static class KanjiMap");
sb.AppendLine("{");
sb.AppendLine("    public static IReadOnlyDictionary<char, char> Entries { get; } = new Dictionary<char, char>");
sb.AppendLine("    {");
foreach (var (zh, jp) in active)
    sb.AppendLine($"        ['\\u{(int)zh:X4}'] = '\\u{(int)jp:X4}', // {zh} -> {jp}");
sb.AppendLine("    };");
sb.AppendLine();
sb.AppendLine($"    public static int Count => {active.Count};");
sb.AppendLine("}");
sb.AppendLine();

Directory.CreateDirectory(Path.GetDirectoryName(outPath)!);
File.WriteAllText(outPath, sb.ToString(), new UTF8Encoding(encoderShouldEmitUTF8Identifier: false));
Console.WriteLine($"Wrote {outPath}");

static int CodePointFromUtf8Int32(int n)
{
    if ((n & 0xFFFFFF80) == 0)
        return n & 0x7F;
    if ((n & 0xFFFFE0C0) == 0xC080)
        return (((n >> 8) & 0x1F) << 6) | ((n >> 0) & 0x3F);
    if ((n & 0xF0C0C0) == 0xE08080)
        return (((n >> 16) & 0x0F) << 12) | (((n >> 8) & 0x3F) << 6) | ((n >> 0) & 0x3F);
    if ((n & unchecked((int)0xF8C0C0C0)) == unchecked((int)0xF0808080))
        return (((n >> 24) & 0x07) << 18) | (((n >> 16) & 0x3F) << 12) | (((n >> 8) & 0x3F) << 6) | ((n >> 0) & 0x3F);
    return 0xFFFF;
}

static string? FindRepoRoot()
{
    foreach (var start in new[] { Directory.GetCurrentDirectory(), AppContext.BaseDirectory })
    {
        for (var dir = new DirectoryInfo(start); dir != null; dir = dir.Parent)
        {
            if (File.Exists(Path.Combine(dir.FullName, "NoMoreEquals.sln")))
                return dir.FullName;
        }
    }

    return null;
}

/// <summary>
/// Locates a local FFXIV install (game root that contains game/sqpack).
/// Order: XIVLauncher config → common install folders → Steam libraries.
/// </summary>
static class FfxivLocator
{
    public static string? FindInstallPath()
    {
        foreach (var candidate in EnumerateCandidates())
        {
            if (IsValidGameRoot(candidate))
                return Path.GetFullPath(candidate);
        }

        return null;
    }

    static IEnumerable<string> EnumerateCandidates()
    {
        foreach (var path in ReadXivLauncherGamePaths())
            yield return path;

        var programFilesX86 = Environment.GetFolderPath(Environment.SpecialFolder.ProgramFilesX86);
        var programFiles = Environment.GetFolderPath(Environment.SpecialFolder.ProgramFiles);
        foreach (var root in new[] { programFilesX86, programFiles })
        {
            if (string.IsNullOrEmpty(root))
                continue;
            yield return Path.Combine(root, "SquareEnix", "FINAL FANTASY XIV - A Realm Reborn");
            yield return Path.Combine(root, "Steam", "steamapps", "common", "FINAL FANTASY XIV Online");
        }

        foreach (var steamRoot in EnumerateSteamLibraryRoots())
        {
            yield return Path.Combine(steamRoot, "steamapps", "common", "FINAL FANTASY XIV Online");
            yield return Path.Combine(steamRoot, "steamapps", "common", "FINAL FANTASY XIV - A Realm Reborn");
        }
    }

    static IEnumerable<string> ReadXivLauncherGamePaths()
    {
        var appData = Environment.GetFolderPath(Environment.SpecialFolder.ApplicationData);
        if (string.IsNullOrEmpty(appData))
            yield break;

        var configPath = Path.Combine(appData, "XIVLauncher", "launcherConfigV3.json");
        if (!File.Exists(configPath))
            yield break;

        string json;
        try
        {
            json = File.ReadAllText(configPath);
        }
        catch
        {
            yield break;
        }

        // Prefer System.Text.Json when the file is valid JSON; fall back to a light regex
        // because some launcher builds have written slightly non-strict configs.
        string? gamePath = null;
        try
        {
            using var doc = JsonDocument.Parse(json);
            if (doc.RootElement.TryGetProperty("GamePath", out var prop))
                gamePath = prop.GetString();
        }
        catch (JsonException)
        {
            var m = Regex.Match(json, "\"GamePath\"\\s*:\\s*\"([^\"]+)\"");
            if (m.Success)
                gamePath = Regex.Unescape(m.Groups[1].Value);
        }

        if (!string.IsNullOrWhiteSpace(gamePath))
            yield return gamePath;
    }

    static IEnumerable<string> EnumerateSteamLibraryRoots()
    {
        var programFilesX86 = Environment.GetFolderPath(Environment.SpecialFolder.ProgramFilesX86);
        if (string.IsNullOrEmpty(programFilesX86))
            yield break;

        var steamRoot = Path.Combine(programFilesX86, "Steam");
        yield return steamRoot;

        var vdf = Path.Combine(steamRoot, "steamapps", "libraryfolders.vdf");
        if (!File.Exists(vdf))
            yield break;

        string text;
        try
        {
            text = File.ReadAllText(vdf);
        }
        catch
        {
            yield break;
        }

        // libraryfolders.vdf: "path"  "D:\\SteamLibrary"
        foreach (Match m in Regex.Matches(text, "\"path\"\\s+\"([^\"]+)\""))
        {
            var path = m.Groups[1].Value.Replace(@"\\", @"\");
            if (!string.IsNullOrWhiteSpace(path))
                yield return path;
        }
    }

    static bool IsValidGameRoot(string? path)
    {
        if (string.IsNullOrWhiteSpace(path))
            return false;
        try
        {
            return Directory.Exists(Path.Combine(path, "game", "sqpack"));
        }
        catch
        {
            return false;
        }
    }
}
