#!/usr/bin/env python3
"""Generate KanjiCandidates.cs from OpenCC JPShinjitaiCharacters.txt.

OpenCC's file maps Japanese shinjitai -> traditional/kyujitai variants.
We reverse it to Chinese/kyujitai -> Japanese candidates. At runtime the
plugin filters these against AXIS font glyph coverage so characters that
already render (國, 學, 圖, 邊, ...) are left alone.
"""

from __future__ import annotations

import pathlib

ROOT = pathlib.Path(__file__).resolve().parents[1]
SRC = ROOT / "_tmp_opencc" / "data" / "dictionary" / "JPShinjitaiCharacters.txt"
OUT = ROOT / "NoMoreEquals" / "Data" / "KanjiCandidates.cs"

# Extra zh->jp pairs commonly missing from AXIS but not always in OpenCC reverse.
EXTRAS: dict[str, str] = {
    "綠": "緑",
    "绿": "緑",
    "黑": "黒",
    "每": "毎",
}


def load_reversed(path: pathlib.Path) -> dict[str, str]:
    rev: dict[str, str] = {}
    text = path.read_text(encoding="utf-8")
    for line in text.splitlines():
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        parts = line.split("\t")
        if len(parts) < 2:
            continue
        jp = parts[0]
        for zh in parts[1].split():
            if len(jp) == 1 and len(zh) == 1 and zh != jp:
                rev.setdefault(zh, jp)
    return rev


def main() -> None:
    if not SRC.is_file():
        raise SystemExit(f"Missing OpenCC dictionary: {SRC}")

    mapping = load_reversed(SRC)
    mapping.update(EXTRAS)

    # Drop identity / non-BMP
    mapping = {
        k: v
        for k, v in mapping.items()
        if len(k) == 1 and len(v) == 1 and k != v and ord(k) <= 0xFFFF and ord(v) <= 0xFFFF
    }

    items = sorted(mapping.items(), key=lambda kv: ord(kv[0]))
    OUT.parent.mkdir(parents=True, exist_ok=True)

    lines = [
        "// <auto-generated />",
        "// Candidate Chinese/kyujitai -> Japanese mappings (OpenCC JPShinjitai, reversed).",
        "// Runtime filters against AXIS .fdt glyph coverage before use.",
        "using System.Collections.Generic;",
        "",
        "namespace NoMoreEquals.Data;",
        "",
        "internal static class KanjiCandidates",
        "{",
        "    /// <summary>Unfiltered candidate pairs. Runtime narrows these down via <see cref=\"KanjiMap\"/>.</summary>",
        "    public static IReadOnlyDictionary<char, char> Entries { get; } = new Dictionary<char, char>",
        "    {",
    ]
    for zh, jp in items:
        lines.append(f"        ['\\u{ord(zh):04X}'] = '\\u{ord(jp):04X}', // {zh} -> {jp}")
    lines += [
        "    };",
        "}",
        "",
    ]
    OUT.write_text("\n".join(lines), encoding="utf-8")
    print(f"Wrote {len(items)} candidates to {OUT}")
    for sample in ("綠", "绿", "黑", "每", "圖", "邊", "國", "學"):
        mapped = mapping.get(sample)
        if mapped is None:
            print(f"  U+{ord(sample):04X} -> MISSING")
        else:
            print(f"  U+{ord(sample):04X} -> U+{ord(mapped):04X}")


if __name__ == "__main__":
    main()
